name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        next-version:
          [
            "14.0",
            "14.1",
            "14.2",
            "15.0",
            "15.1",
            "15.2",
            "15.3",
            "15.4",
            "15.5",
            "16.0",
          ]
        node-version: [20]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Update Next.js version in example
        run: pnpm add next@~${{ matrix.next-version }} --save-exact
        working-directory: example

      - name: Build example app
        run: pnpm build
        working-directory: example

      - name: Run example app
        run: pnpm start &
        working-directory: example

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps --only-shell

      - name: Wait for server ready
        run: curl --fail --retry 10 --retry-delay 1 --retry-all-errors --silent --output /dev/null --head http://localhost:3000

      - name: Run Playwright tests
        run: PORT=3000 pnpm playwright test

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-next-${{ matrix.next-version }}
          path: playwright-report/
          retention-days: 30
